### ISSUE TITLE
Populate the client config

### ISSUE THREAD

**Issue by jaxxstorm** [cristifalcas/puppet-kubernetes#11]
Currently `kubernetes::client` seems to clear all the vars in `/etc/kubernetes/config`

Is there a reason for this? I can send a PR to set the values in there if we think it's useful, but don't want to assume it was done for no reason.

**Comment by cristifalcas** [comment]
All configuration is done via the specific class (kubelet. kube-apiserver, etc). It will be confusing to have maybe different configuration in /etc/kubernetes/config.

Do you have any specific variables that you think should be in there?
