### ISSUE TITLE
flag --apiserver-count unknown

### ISSUE THREAD

**Issue by zdtsw** [cristifalcas/puppet-kubernetes#13]
Hi,

in the templates, it sets flag 
--apiserver-count 
--delete-collection-workers
--etcd-quorum-read
--kubernetes-service-node-port
--repair-malformed-updates
--watch-cache
but they are all unknown arguments for latest version of kube-apiserver (download by yum package on centos7)
could you remove them?

We do not wanna manually update template every time, if we try to pull your new commits.
But if we include this kubernetes module, then it would consistent with these arguments there

**Comment by cristifalcas** [comment]
What kubernetes version are you using?

**Comment by zdtsw** [comment]
kubernetes-client.x86_64 1.1.0-0.4.git2bfa9a1.el7
kubernetes-master.x86_64 1.1.0-0.4.git2bfa9a1.el7
kubernetes.x86_64 1.1.0-0.4.git2bfa9a1.el7
kubernetes-node.x86_64 1.1.0-0.4.git2bfa9a1.el7
kubernetes-unit-test.x86_64 1.1.0-0.4.git2bfa9a1.el7

these are the version by default puppet downloaded for centos7.
 we just wonder how it can be ran on centos7. 
version for kube-apiserver is v1.1.0-alpha.0.1464+2bfa9a1f98147c

**Comment by cristifalcas** [comment]
You should use version 1.4.0 of this module. After that version the parameter of the module are kept current with the latest kubernetes version only.

Until (and including) 1.4.0 there is a parameter named "minimum_version" that will set only the valid parameters on the config files for that kubernetes version.

You need to set minimum_version to 1.1
